### ISSUE TITLE
Revisione projet plan

### ISSUE THREAD

**Issue by jacopobellosi** [jacopobellosi/UniPac-Man#1]
Ci faccia sapere cosa ne pensa

**Comment by garganti** [comment]
Va bene anche se alcune cose un po' vaghe. Ad esempio non ho capito che tipo di applicazione è. E' una app android? Web? Testuale?
Su Agile siete un po' vaghi - datevi un po' un processo, tipo SCRUM se volete, oppure XP ... Magari iterativa con dei cicli. Prevedete l'uso di backlog? Che ruoli avete tra di voi?
Anche sugli standard, javadoc va bene ma solo quello?

**Comment by garganti** [comment]
Ah ho trovato dove dite che usate swing. OK ho capito.
